import { useRef, useState } from 'react';
import { getMatchingWorkers, householdCategories } from '../data/household';
import { WORKER_PENDING, emptyOtp, loadSession, normalizePhone, otpIsComplete, phoneIsValid, saveSession } from '../lib/session';
import type { AdminCredentials, AppActions, AppPage, AppState, CustomerRegistration, DashboardContent, HouseholdCategory, Role, Session, WorkerFilter, WorkerProfile, WorkerRegistration } from '../types';

const emptyCustomerRegistration = (): CustomerRegistration => ({ step: 1, name: '', phone: '', otpSent: false });
const emptyWorkerRegistration = (): WorkerRegistration => ({ step: 1, name: '', phone: '', otpSent: false, aadhaar: '', aadhaarOtp: '', aadhaarVerified: false, skills: [], experience: '', consented: false });
const dashboardContent = (role: Role, searchTitle: string): DashboardContent => ({
  heading: role === 'worker' ? 'Your next opportunity is waiting.' : role === 'admin' ? 'Platform at a glance.' : searchTitle ? `Help for “${searchTitle}”` : 'Find trusted help nearby.',
  copy: role === 'worker' ? 'Discover local work that matches your skills and availability.' : role === 'admin' ? 'Review new profiles and keep your local network thriving.' : searchTitle ? 'We’ll match you with trusted local professionals for this task.' : 'Search for a service or browse recommendations for your next task.',
  taskTitle: role === 'worker' ? 'Jobs matching your skills' : role === 'admin' ? '12 profiles are ready for review' : searchTitle ? `Top matches for ${searchTitle}` : 'Home & repairs',
  taskText: role === 'worker' ? 'See verified requests close to your current location.' : role === 'admin' ? 'Open the verification queue to continue.' : searchTitle ? 'Verified workers near your current location.' : 'Find skilled local professionals.',
});

export function useLabouRackApp(): { state: AppState; actions: AppActions } {
  const [page, setPage] = useState<AppPage>('login');
  const [role, setRole] = useState<Role>('customer');
  const [session, setSession] = useState<Session>(loadSession);
  const [phone, setPhone] = useState(''); const [admin, setAdmin] = useState<AdminCredentials>({ id: '', password: '' }); const [otp, setOtp] = useState<string[]>(emptyOtp); const [toast, setToast] = useState('');
  const [customerRegistration, setCustomerRegistration] = useState<CustomerRegistration>(emptyCustomerRegistration); const [workerRegistration, setWorkerRegistration] = useState<WorkerRegistration>(emptyWorkerRegistration); const [profileOpen, setProfileOpen] = useState(false); const [searchQuery, setSearchQuery] = useState(''); const [searchTitle, setSearchTitle] = useState('');
  const [homeRepair, setHomeRepair] = useState<{ view: 'home' | 'categories' | 'issues' | 'workers'; category: HouseholdCategory | null; issue: string; filter: WorkerFilter }>({ view: 'home', category: null, issue: '', filter: 'all' });
  const toastTimer = useRef<number>(); const otpRefs = useRef<(HTMLInputElement | null)[]>([]);
  const showToast = (message: string) => { setToast(message); window.clearTimeout(toastTimer.current); toastTimer.current = window.setTimeout(() => setToast(''), 2800); };
  const updateSession = (values: Partial<Session>) => { const next = { ...session, ...values }; setSession(next); saveSession(next); };
  const updateCustomer = (values: Partial<CustomerRegistration>) => setCustomerRegistration(current => ({ ...current, ...values }));
  const updateWorker = (values: Partial<WorkerRegistration>) => setWorkerRegistration(current => ({ ...current, ...values }));
  const workers = getMatchingWorkers(homeRepair.category, homeRepair.issue).filter(worker => homeRepair.filter === 'nearby' ? worker.distance <= 3 : homeRepair.filter === 'rated' ? worker.rating >= 4.8 : homeRepair.filter === 'available' ? worker.status === 'Available now' : true);
  const actions: AppActions = {
    setRole, setPhone: value => setPhone(normalizePhone(value)), setAdminId: id => setAdmin(current => ({ ...current, id })), setAdminPassword: password => setAdmin(current => ({ ...current, password })),
    setOtpInputRef: (index, node) => { otpRefs.current[index] = node; },
    setOtpDigit: (index, value) => { const digit = value.replace(/\D/g, '').slice(0, 1); const next = [...otp]; next[index] = digit; setOtp(next); if (digit) otpRefs.current[index + 1]?.focus(); },
    pasteOtp: event => { event.preventDefault(); const digits = event.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6).split(''); setOtp([...digits, ...emptyOtp()].slice(0, 6)); otpRefs.current[Math.min(digits.length, 5)]?.focus(); },
    focusPreviousOtp: (index, isEmpty) => { if (isEmpty) otpRefs.current[index - 1]?.focus(); },
    login: event => { event.preventDefault(); if (role === 'admin') { if (!admin.id.trim() || !admin.password) return showToast('Enter your admin ID and password to continue.'); updateSession({ role: 'admin', name: 'LabouRack administrator' }); return setPage('dashboard'); } if (!phoneIsValid(phone)) return showToast('Please enter a valid 10-digit mobile number.'); updateSession({ role, phone }); setOtp(emptyOtp()); setPage('otp'); },
    startRegistration: () => { setOtp(emptyOtp()); if (role === 'worker') { setWorkerRegistration(emptyWorkerRegistration()); setPage('worker-registration'); } else { setCustomerRegistration(emptyCustomerRegistration()); setPage('customer-registration'); } },
    verifyLoginOtp: event => { event.preventDefault(); if (!otpIsComplete(otp)) return showToast('Enter the complete 6-digit OTP.'); if (role === 'worker' && session.workerVerification === WORKER_PENDING) return setPage('worker-pending'); setPage('dashboard'); },
    resendOtp: () => showToast('A fresh code is on its way.'), showToast, goToLogin: () => setPage('login'),
    setCustomerName: name => updateCustomer({ name }), setCustomerPhone: value => updateCustomer({ phone: normalizePhone(value), otpSent: false }),
    sendCustomerOtp: () => { if (!phoneIsValid(customerRegistration.phone)) return showToast('Enter a valid 10-digit mobile number first.'); updateCustomer({ otpSent: true }); setOtp(emptyOtp()); showToast('OTP sent to your mobile number.'); },
    submitCustomerRegistration: event => { event.preventDefault(); if (customerRegistration.step === 1) { if (!customerRegistration.name.trim()) return showToast('Please enter your full name.'); if (!phoneIsValid(customerRegistration.phone)) return showToast('Enter a valid 10-digit mobile number.'); if (!customerRegistration.otpSent) return showToast('Send an OTP to verify your mobile number.'); return updateCustomer({ step: 2 }); } if (!otpIsComplete(otp)) return showToast('Enter the complete 6-digit OTP.'); updateSession({ role: 'customer', name: customerRegistration.name.trim(), phone: customerRegistration.phone, location: 'Bengaluru, Karnataka', workerVerification: null }); setRole('customer'); setPage('success'); },
    backCustomerRegistration: () => updateCustomer({ step: 1 }),
    setWorkerName: name => updateWorker({ name }), setWorkerPhone: value => updateWorker({ phone: normalizePhone(value), otpSent: false }), setWorkerAadhaar: value => updateWorker({ aadhaar: value.replace(/\D/g, '').slice(0, 12), aadhaarVerified: false }), setWorkerAadhaarOtp: value => updateWorker({ aadhaarOtp: value.replace(/\D/g, '').slice(0, 6) }), setWorkerExperience: experience => updateWorker({ experience }), setWorkerConsent: consented => updateWorker({ consented }),
    sendWorkerOtp: () => { if (!phoneIsValid(workerRegistration.phone)) return showToast('Enter a valid 10-digit mobile number first.'); updateWorker({ otpSent: true }); setOtp(emptyOtp()); showToast('OTP sent to your mobile number.'); },
    verifyAadhaar: () => { if (workerRegistration.aadhaar.length !== 12) return showToast('Enter a valid 12-digit Aadhaar number first.'); updateWorker({ aadhaarVerified: true }); showToast('Aadhaar number verified.'); },
    toggleWorkerSkill: skill => updateWorker({ skills: workerRegistration.skills.includes(skill) ? workerRegistration.skills.filter(item => item !== skill) : [...workerRegistration.skills, skill] }),
    submitWorkerRegistration: event => { event.preventDefault(); const r = workerRegistration; if (r.step === 1) { if (!r.name.trim()) return showToast('Please enter your full name.'); if (!phoneIsValid(r.phone)) return showToast('Enter a valid 10-digit mobile number.'); if (!r.otpSent) return showToast('Send an OTP to verify your mobile number.'); return updateWorker({ step: 2 }); } if (r.step === 2) { if (!otpIsComplete(otp)) return showToast('Enter the complete 6-digit OTP.'); return updateWorker({ step: 3 }); } if (r.step === 3) { if (!r.aadhaarVerified) return showToast('Verify your Aadhaar number to continue.'); if (r.aadhaarOtp.length !== 6) return showToast('Enter the 6-digit Aadhaar verification code.'); return updateWorker({ step: 4 }); } if (!r.skills.length) return showToast('Choose at least one skill.'); if (!r.experience.trim()) return showToast('Tell us a little about your experience.'); if (!r.consented) return showToast('Please confirm your information to submit your profile.'); updateSession({ role: 'worker', name: r.name.trim(), phone: r.phone, location: 'Bengaluru, Karnataka', skills: r.skills, experience: r.experience.trim(), workerVerification: WORKER_PENDING }); setRole('worker'); setPage('worker-pending'); },
    backWorkerRegistration: () => updateWorker({ step: (workerRegistration.step - 1) as WorkerRegistration['step'] }), continueToDashboard: () => setPage('dashboard'), toggleProfile: () => setProfileOpen(open => !open), signOut: () => { setProfileOpen(false); setPage('login'); },
    setSearchQuery, searchDashboard: event => { event.preventDefault(); if (!searchQuery.trim()) return showToast('Tell us what you need help with.'); const title = searchQuery.trim(); setSearchTitle(title); showToast(`Searching nearby professionals for “${title}”.`); },
    openHomeRepair: () => setHomeRepair({ view: 'categories', category: null, issue: '', filter: 'all' }), chooseHouseholdCategory: category => setHomeRepair({ view: 'issues', category, issue: '', filter: 'all' }), chooseHouseholdIssue: issue => setHomeRepair(current => ({ ...current, view: 'workers', issue })),
    openPopularProblem: (categoryId, issue) => { const category = householdCategories.find(item => item.id === categoryId); if (category) setHomeRepair({ view: 'workers', category, issue, filter: 'all' }); },
    goBackInHomeRepair: () => setHomeRepair(current => current.view === 'workers' ? { ...current, view: 'issues', issue: '', filter: 'all' } : current.view === 'issues' ? { view: 'categories', category: null, issue: '', filter: 'all' } : { view: 'home', category: null, issue: '', filter: 'all' }), closeHomeRepair: () => setHomeRepair({ view: 'home', category: null, issue: '', filter: 'all' }), setWorkerFilter: filter => setHomeRepair(current => ({ ...current, filter })), bookWorker: worker => showToast(`Booking request sent to ${worker.name}.`), notifyWorker: worker => showToast(`We’ll notify you when ${worker.name} is available.`),
  };
  return { state: { page, role, session, phone, admin, otp, toast, customerRegistration, workerRegistration, profileOpen, searchQuery, dashboard: dashboardContent(role, searchTitle), homeRepair: { ...homeRepair, workers } }, actions };
}
