import type { ReactNode } from 'react';
import type { AppActions } from '../types';

export function Brand({ compact = false }: { compact?: boolean }) { return <a className={compact ? 'dashboard-brand' : 'auth-brand'} href="#" onClick={event => event.preventDefault()}><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span>LabouRack</span></a>; }
export function Toast({ message }: { message: string }) { return message ? <div className="toast" role="status">{message}</div> : null; }
export function AuthShell({ children }: { children: ReactNode }) { return <main className="app-shell"><section className="auth-panel" aria-live="polite"><div className="auth-topbar"><Brand /></div>{children}</section></main>; }
export function OtpInputs({ otp, actions }: { otp: string[]; actions: AppActions }) { return <div className="otp-inputs" aria-label="One-time password">{otp.map((digit, index) => <input key={index} ref={node => actions.setOtpInputRef(index, node)} value={digit} inputMode="numeric" maxLength={1} aria-label={`Digit ${index + 1}`} autoFocus={index === 0} onChange={event => actions.setOtpDigit(index, event.target.value)} onKeyDown={event => event.key === 'Backspace' && actions.focusPreviousOtp(index, !digit)} onPaste={actions.pasteOtp} />)}</div>; }
export function Progress({ worker, step }: { worker: boolean; step: number }) { const labels = worker ? ['Your details', 'Verify mobile', 'Verify identity', 'Your profile'] : ['Your details', 'Verify mobile']; return <div className="progress-steps" aria-label="Registration steps">{labels.map((label, index) => <div key={label} className={'step ' + (index + 1 < step ? 'done' : index + 1 === step ? 'active' : '')}>{label}</div>)}</div>; }
export function RegistrationShell({ worker = false, step, onBack, children }: { worker?: boolean; step: number; onBack: () => void; children: ReactNode }) { return <AuthShell><div className="flow-view"><button className="back-button" type="button" onClick={onBack}>← <span>Back to sign in</span></button><div className="auth-heading compact"><p className="eyebrow">{worker ? 'WORKER REGISTRATION' : 'CUSTOMER REGISTRATION'}</p><h1>{worker ? 'Build your worker profile.' : 'Create your account.'}</h1><p>{worker ? 'Help customers trust your skills and get discovered for great local work.' : 'A few details and you’ll be ready to post your first task.'}</p></div><Progress worker={worker} step={step} />{children}</div></AuthShell>; }
